version: "3.8"

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto_container
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - iot
  
  influxdb:
    image: influxdb:1.8
    container_name: influxdb_container
    restart: always
    ports:
      - 8086:8086
    networks:
      - iot
    volumes:
      - ./influxdb_data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=telegraf
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=secretpassword
      - INFLUXDB_USER=telegraf
      - INFLUXDB_USER_PASSWORD=secretpassword
  
  telegraf:
    image: telegraf
    container_name: telegraf_container
    restart: always
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - mosquitto
      - influxdb
    networks:
      - iot
    
  
  grafana:
    image: grafana/grafana
    container_name: grafana_container
    restart: always
    ports:
      - "3000:3000"
    networks:
      - iot
    volumes:
      - ./grafana_data:/var/lib/grafana
      - ./grafana_conf/defaults.ini:/usr/share/grafana/conf/defaults.ini
    depends_on:
      - influxdb

  bridge:
    image: migoller/http-mqtt-bridge:latest
    container_name: bridge_container
    restart: always
    ports:
      - "5678:5000"
    networks:
      - iot
    environment:
      - AUTH_KEY=912ec803b2ce49e4a541068d495ab570
      - MQTT_HOST=tcp://mosquitto:1883

  water-system-planner:
    image: water-system-planner
    restart: always
    build:
      context: ./water-system-planner/
      dockerfile: Dockerfile
    volumes:
      - /data/water-system-planner
    ports:
      - "8081:8081"
    networks:
      - iot

networks:
  iot: